Added default constructor to avoid -Weffc++ warning
/usr/bin/g++-4.8   -DSEXP_USE_LOCALE -isystem /home/travis/build/lispparser/sexp-cpp/external/googletest/googletest/include -isystem /home/travis/build/lispparser/sexp-cpp/include  -g   -std=c++11 -pedantic -Wall -Wextra -Wno-c++0x-compat -Wnon-virtual-dtor -Wshadow -Wcast-qual -Winit-self -Wno-unused-parameter -Weffc++ -Wconversion -Wold-style-cast -Werror -o CMakeFiles/test_sexp.dir/tests/parser_test.cpp.o -c /home/travis/build/lispparser/sexp-cpp/tests/parser_test.cpp
/home/travis/build/lispparser/sexp-cpp/tests/parser_test.cpp: In constructor ‘ParserLocaleTest::ParserLocaleTest()’:
/home/travis/build/lispparser/sexp-cpp/tests/parser_test.cpp:147:7: error: ‘ParserLocaleTest::m_oldlocale’ should be initialized in the member initialization list [-Werror=effc++]
 class ParserLocaleTest : public ::testing::Test
       ^